/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bet4money;

import java.awt.Component;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import gamelogic.*;

/**
 *
 * @author pedro
 */
@SuppressWarnings("serial")
public class game extends javax.swing.JFrame {
	Component jFrame;
	jogo jogo; 
	data data;
    int aux=0;
    /**
     * Creates new form game
     */
    public game(data indata) {
    	this.jFrame = null;
    	this.jogo = new jogo();
    	this.data = indata;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        rules_button = new javax.swing.JButton();
        double_button = new javax.swing.JButton();
        hit_button = new javax.swing.JButton();
        stand_button = new javax.swing.JButton();
        split_button = new javax.swing.JButton();
        deal_button = new javax.swing.JButton();
        split_count = new javax.swing.JLabel();
        dealer_count = new javax.swing.JLabel();
        player_count = new javax.swing.JLabel();
        deck = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        player3 = new javax.swing.JLabel();
        player4 = new javax.swing.JLabel();
        player5 = new javax.swing.JLabel();
        player6 = new javax.swing.JLabel();
        player7 = new javax.swing.JLabel();
        split1 = new javax.swing.JLabel();
        split2 = new javax.swing.JLabel();
        split3 = new javax.swing.JLabel();
        split4 = new javax.swing.JLabel();
        split5 = new javax.swing.JLabel();
        split6 = new javax.swing.JLabel();
        split7 = new javax.swing.JLabel();
        dealer1 = new javax.swing.JLabel();
        dealer2 = new javax.swing.JLabel();
        dealer3 = new javax.swing.JLabel();
        dealer4 = new javax.swing.JLabel();
        dealer5 = new javax.swing.JLabel();
        dealer6 = new javax.swing.JLabel();
        dealer7 = new javax.swing.JLabel();
        
        java.net.URL iconURL = getClass().getResource("/img/smalllogo.jpg");
        // iconURL is null when not found
        ImageIcon icon = new ImageIcon(iconURL);
        setIconImage(icon.getImage());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bet4Money");
        setResizable(false);
        setSize(new java.awt.Dimension(960, 683));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setPreferredSize(new java.awt.Dimension(960, 683));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/smalllogo.jpg"))); // NOI18N

        back_button.setBackground(new java.awt.Color(255, 255, 255));
        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/setaa.png"))); // NOI18N
        back_button.setBorder(null);
        back_button.setBorderPainted(false);
        back_button.setContentAreaFilled(false);
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        rules_button.setBackground(new java.awt.Color(255, 255, 255));
        rules_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/~klivro.png"))); // NOI18N
        rules_button.setAlignmentY(0.0F);
        rules_button.setBorder(null);
        rules_button.setBorderPainted(false);
        rules_button.setContentAreaFilled(false);
        rules_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rules_buttonActionPerformed(evt);
            }
        });

        double_button.setBackground(new java.awt.Color(54, 69, 79));
        double_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        double_button.setForeground(new java.awt.Color(255, 255, 255));
        double_button.setText("DOUBLE");
        double_button.setAlignmentY(0.0F);
        double_button.setBorder(null);
        double_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                double_buttonActionPerformed(evt);
            }
        });

        hit_button.setBackground(new java.awt.Color(180, 180, 180));
        hit_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        hit_button.setForeground(new java.awt.Color(255, 255, 255));
        hit_button.setText("HIT");
        hit_button.setAlignmentY(0.0F);
        hit_button.setBorder(null);
        hit_button.setBorderPainted(false);
        hit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hit_buttonActionPerformed(evt);
            }
        });

        stand_button.setBackground(new java.awt.Color(180, 180, 180));
        stand_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        stand_button.setForeground(new java.awt.Color(255, 255, 255));
        stand_button.setText("STAND");
        stand_button.setAlignmentY(0.0F);
        stand_button.setBorder(null);
        stand_button.setBorderPainted(false);
        stand_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stand_buttonActionPerformed(evt);
            }
        });

        split_button.setBackground(new java.awt.Color(54, 69, 79));
        split_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        split_button.setForeground(new java.awt.Color(255, 255, 255));
        split_button.setText("SPLIT");
        split_button.setAlignmentY(0.0F);
        split_button.setBorder(null);
        split_button.setBorderPainted(false);
        split_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                split_buttonActionPerformed(evt);
            }
        });

        deal_button.setBackground(new java.awt.Color(90, 121, 148));
        deal_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        deal_button.setForeground(new java.awt.Color(255, 255, 255));
        deal_button.setText("NEW GAME");
        deal_button.setAlignmentY(0.0F);
        deal_button.setBorder(null);
        deal_button.setBorderPainted(false);
        deal_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deal_buttonActionPerformed(evt);
            }
        });

        split_count.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        split_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        split_count.setPreferredSize(new java.awt.Dimension(50, 50));

        dealer_count.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        dealer_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dealer_count.setText("0");
        dealer_count.setPreferredSize(new java.awt.Dimension(50, 50));

        player_count.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        player_count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player_count.setText("0");
        player_count.setPreferredSize(new java.awt.Dimension(50, 50));

        deck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/card_back.jpg"))); // NOI18N

        player1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       
        player2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        player3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        player4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        player5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        player6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        player7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        split7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        dealer7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(logo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(back_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 784, Short.MAX_VALUE)
                        .addComponent(rules_button))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealer_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(split_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(split1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dealer1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(split2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(split3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(split4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dealer2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dealer3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(dealer4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(2, 2, 2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(double_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(hit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stand_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(split5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(split6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(player5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(player6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dealer5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dealer6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dealer7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(split7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(player7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(152, 152, 152)
                                .addComponent(deck, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(split_button, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(deal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(357, 357, 357))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rules_button)
                            .addComponent(back_button))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dealer_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dealer1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dealer7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(split1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(split7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(deck)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(split_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(player_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(player1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(player7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(160, 160, 160))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(double_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stand_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(split_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)))
                .addComponent(deal_button, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String getstring(int carta, int suit, int figure) {
    	String r= "";
    	String aux="";
    	if(suit ==1) {
    		aux = "spades";
    	}
    	if(suit ==2) {
    		aux = "clubs";
    	}
    	if(suit ==3) {
    		aux = "hearts";
    	}
    	if(suit ==4) {
    		aux = "diamonds";
    	}
    	if(carta == 1) {
    		r= String.format("/img/ace_of_%s.png", aux);
    	}
    	if(carta == 1 && suit==1) {
    		r= String.format("/img/ace_of_%s2.png", aux);
    	}
    	if(carta > 1 && carta <10) {
    		r= String.format("/img/%d_of_%s.png", carta, aux);
    	}
    	if(carta == 10 && figure==10) {
    		r= String.format("/img/jack_of_%s2.png", aux);
    	}
    	if(carta == 10 && figure==11) {
    		r= String.format("/img/queen_of_%s2.png", aux);
    	}
    	if(carta == 10 && figure==12) {
    		r= String.format("/img/king_of_%s2.png", aux);
    	}
    	if(carta == 10 && figure==13) {
    		r= String.format("/img/10_of_%s.png", aux);
    	}
    	
    	return r;
    };
    
    private void print() {
    	player_count.setText(Integer.toString(jogo.player.num));
  	    dealer_count.setText(Integer.toString(jogo.dealer.num));
  	    split_count.setText(Integer.toString(jogo.split.num));
  	    if(jogo.split.num==0) {
  	    	split_count.setText("");
  	    }
  	  
  	    player1.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[0], jogo.player.suit[0], jogo.player.figure[0])))); // NOI18N
  	    player2.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[1], jogo.player.suit[1], jogo.player.figure[1])))); // NOI18N
  	    player3.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[2], jogo.player.suit[2], jogo.player.figure[2])))); // NOI18N
  	    player4.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[3], jogo.player.suit[3], jogo.player.figure[3])))); // NOI18N
  	    player5.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[4], jogo.player.suit[4], jogo.player.figure[4])))); // NOI18N
  	    player6.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[5], jogo.player.suit[5], jogo.player.figure[5])))); // NOI18N
  	    player7.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.player.cards[6], jogo.player.suit[6], jogo.player.figure[6])))); // NOI18N
  	    
  	 	dealer1.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[0], jogo.dealer.suit[0], jogo.dealer.figure[0])))); // NOI18N
  	 	dealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[1], jogo.dealer.suit[1], jogo.dealer.figure[1])))); // NOI18N
  	 	if(jogo.dealer.cards[0]!=0 && jogo.dealer.cards[1]==0) {
  	 		dealer2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/card_back.jpg"))); // NOI18N
  	 	}
  	 	dealer3.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[2], jogo.dealer.suit[2], jogo.dealer.figure[2])))); // NOI18N
  	 	dealer4.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[3], jogo.dealer.suit[3], jogo.dealer.figure[3])))); // NOI18N
  	 	dealer5.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[4], jogo.dealer.suit[4], jogo.dealer.figure[4])))); // NOI18N
  	 	dealer6.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[5], jogo.dealer.suit[5], jogo.dealer.figure[5])))); // NOI18N
  	 	dealer7.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.dealer.cards[6], jogo.dealer.suit[6], jogo.dealer.figure[6])))); // NOI18N
  	 	
  	 	split1.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[0], jogo.split.suit[0], jogo.split.figure[0])))); // NOI18N
  	 	split2.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[1], jogo.split.suit[1], jogo.split.figure[1])))); // NOI18N
  	 	split3.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[2], jogo.split.suit[2], jogo.split.figure[2])))); // NOI18N
  	 	split4.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[3], jogo.split.suit[3], jogo.split.figure[3])))); // NOI18N
  	 	split5.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[4], jogo.split.suit[4], jogo.split.figure[4])))); // NOI18N
  	 	split6.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[5], jogo.split.suit[5], jogo.split.figure[5])))); // NOI18N
  	 	split7.setIcon(new javax.swing.ImageIcon(getClass().getResource(getstring(jogo.split.cards[6], jogo.split.suit[6], jogo.split.figure[6])))); // NOI18N
    }
    /*
    public void dealer() {
		do {
			if(jogo.dealer.num<17) {
				jogo.dealer.hit();
				//System.out.println(jogo.dealer.cards[1]);
				print();
				System.out.println("OIIIIIIIIIIIII");
				try
				{
				    Thread.sleep(2000);
				}
				catch(InterruptedException ex)
				{
				    Thread.currentThread().interrupt();
				}
			}
			if(jogo.dealer.num>16) {
				jogo.dealer.stand();
			}
		}while(!jogo.dealer.stand);
	}
    */
    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        new PlayAccount(data).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void rules_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rules_buttonActionPerformed
        new rules().setVisible(true);
    }//GEN-LAST:event_rules_buttonActionPerformed

    private void hit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hit_buttonActionPerformed
        if(!jogo.player.stand && jogo.gameover == 0) {
        	jogo.player.hit();
			//System.out.println("Your turn!");
			print();
			jogo.isGameOver(); 
			data.updateData(jogo.gameover);//
        }else if(!jogo.split.stand && jogo.state == 0){
        	JOptionPane.showMessageDialog(jFrame, "Split hit");
        	jogo.split.hit();
			//System.out.println("Your turn!");
			print();
			jogo.splitOver(); 
			data.updateData(jogo.state);//
        }else {
			JOptionPane.showMessageDialog(jFrame, "Can't do that right now");
        }
    }//GEN-LAST:event_hit_buttonActionPerformed

    private void deal_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deal_buttonActionPerformed
    	//data.updateData(jogo.gameover);
    	jogo.newGame();
    	if(jogo.player.cards[0] == jogo.player.cards[1] && jogo.player.figure[0] == jogo.player.figure[1]  && jogo.player.cards[2] == 0 && jogo.player.cards[0] != 0) {
    		split_button.setBackground(new java.awt.Color(180, 180, 180));
    	}else {
    		split_button.setBackground(new java.awt.Color(54, 69, 79));
    	}

  	  	print();
  	    jogo.isGameOver(); //IF 21 IS BLACKJACK OTHERWISE NO   
  	    data.updateData(jogo.gameover);//
    }//GEN-LAST:event_deal_buttonActionPerformed

    private void double_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_double_buttonActionPerformed
    	JOptionPane.showMessageDialog(jFrame, "You are not playing for money!");
    }//GEN-LAST:event_double_buttonActionPerformed

    private void stand_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stand_buttonActionPerformed
    	if(jogo.gameover == 0 && jogo.state == -1) {
    		jogo.player.stand();
    		jogo.dealer();//Could do a buffer between dealer plays
			print();
			jogo.isGameOver(); 
			data.updateData(jogo.gameover);//
    	}else if(jogo.state == 0 && !jogo.player.stand){
    		JOptionPane.showMessageDialog(jFrame, "First hand stand!");
    		jogo.player.stand();
			jogo.isGameOver(); 
			data.updateData(jogo.gameover);//
    	}else if(jogo.player.stand && jogo.state == 0){
    		jogo.split.stand();
    		jogo.dealer();//Could do a buffer between dealer plays
			print();
			jogo.isGameOver(); 
			jogo.splitOver(); 
			data.updateData(jogo.gameover);//
			data.updateData(jogo.state);//
    	}else if(jogo.player.stand && jogo.split.stand){
    		jogo.dealer();//Could do a buffer between dealer plays
			print();
			jogo.isGameOver(); 
			jogo.splitOver(); 
			data.updateData(jogo.gameover);//
			data.updateData(jogo.state);//
    	}else {
			JOptionPane.showMessageDialog(jFrame, "Can't do that right now");
        }
    }//GEN-LAST:event_stand_buttonActionPerformed

    private void split_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_split_buttonActionPerformed
    	//JOptionPane.showMessageDialog(jFrame, "To be done");
    	if(jogo.player.cards[0] == jogo.player.cards[1] && jogo.player.figure[0] == jogo.player.figure[1]  && jogo.player.cards[2] == 0 && jogo.player.cards[0] != 0) {
    		jogo.state = 0;
    		jogo.split();
    		print();
    	}else {
			JOptionPane.showMessageDialog(jFrame, "Can't do that right now");
        }
    }//GEN-LAST:event_split_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton back_button;
    public javax.swing.JButton deal_button;
    public javax.swing.JLabel dealer1;
    public javax.swing.JLabel dealer2;
    public javax.swing.JLabel dealer3;
    public javax.swing.JLabel dealer4;
    public javax.swing.JLabel dealer5;
    public javax.swing.JLabel dealer6;
    public javax.swing.JLabel dealer7;
    public javax.swing.JLabel dealer_count;
    public javax.swing.JLabel deck;
    public javax.swing.JButton double_button;
    public javax.swing.JButton hit_button;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel logo;
    public javax.swing.JLabel player1;
    public javax.swing.JLabel player2;
    public javax.swing.JLabel player3;
    public javax.swing.JLabel player4;
    public javax.swing.JLabel player5;
    public javax.swing.JLabel player6;
    public javax.swing.JLabel player7;
    public javax.swing.JLabel player_count;
    public javax.swing.JButton rules_button;
    public javax.swing.JLabel split1;
    public javax.swing.JLabel split2;
    public javax.swing.JLabel split3;
    public javax.swing.JLabel split4;
    public javax.swing.JLabel split5;
    public javax.swing.JLabel split6;
    public javax.swing.JLabel split7;
    public javax.swing.JButton split_button;
    public javax.swing.JLabel split_count;
    public javax.swing.JButton stand_button;
    // End of variables declaration//GEN-END:variables
}
